#!/bin/bash

# Public Proxy Setup Script - Install and configure Nginx reverse proxy on Public_Host
# Forwards internet traffic (ports 80/443) to KYPO_Node at 10.1.2.157

# Source common utilities if available
if [ -f /tmp/scripts/utils.sh ]; then
    source /tmp/scripts/utils.sh
elif [ -f "$(dirname "$0")/utils.sh" ]; then
    source "$(dirname "$0")/utils.sh"
else
    # Minimal logging fallback
    log()         { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"; }
    log_error()   { echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR: $1" >&2; }
    log_warning() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] WARNING: $1" >&2; }
    log_success() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] SUCCESS: $1"; }
fi

# Configuration — override via environment variables
KYPO_NODE_IP="${KYPO_NODE_IP:-10.1.2.157}"
KYPO_PUBLIC_IP="${KYPO_PUBLIC_IP:-42.115.38.85}"

NGINX_CONF_DIR="/etc/nginx/sites-available"
NGINX_ENABLED_DIR="/etc/nginx/sites-enabled"
NGINX_CONF_FILE="$NGINX_CONF_DIR/kypo-proxy"
NGINX_CONF_BACKUP="$NGINX_CONF_DIR/kypo-proxy.bak"

# ─────────────────────────────────────────────
# Task 1: Connectivity checks
# ─────────────────────────────────────────────

# Check TCP connectivity from this host to KYPO_Node ports 80 and 443
check_connectivity() {
    log "Checking TCP connectivity to KYPO_Node (${KYPO_NODE_IP})..."

    local failed=0

    if nc -zw3 "${KYPO_NODE_IP}" 80 2>/dev/null; then
        log "  ✓ ${KYPO_NODE_IP}:80 is reachable"
    else
        log_error "  ✗ Cannot reach ${KYPO_NODE_IP}:80 — port 80 is not reachable"
        failed=1
    fi

    if nc -zw3 "${KYPO_NODE_IP}" 443 2>/dev/null; then
        log "  ✓ ${KYPO_NODE_IP}:443 is reachable"
    else
        log_error "  ✗ Cannot reach ${KYPO_NODE_IP}:443 — port 443 is not reachable"
        failed=1
    fi

    if [ "$failed" -eq 1 ]; then
        log_error "Connectivity check failed. Ensure KYPO_Node is running and ports 80/443 are open."
        log_error "Hint: Check firewall rules and that Traefik is running on ${KYPO_NODE_IP}."
        exit 1
    fi

    log_success "Connectivity to KYPO_Node confirmed on ports 80 and 443"
}

# Check whether ports 80 and 443 on the public IP are already listening
check_local_ports() {
    log "Checking local listening ports on ${KYPO_PUBLIC_IP}..."

    local port80_status port443_status

    if ss -tlnp 2>/dev/null | grep -qE ":80\b"; then
        port80_status="LISTENING"
        log "  Port 80  on ${KYPO_PUBLIC_IP}: ${port80_status}"
    else
        port80_status="NOT LISTENING"
        log "  Port 80  on ${KYPO_PUBLIC_IP}: ${port80_status} (Nginx will bind it)"
    fi

    if ss -tlnp 2>/dev/null | grep -qE ":443\b"; then
        port443_status="LISTENING"
        log "  Port 443 on ${KYPO_PUBLIC_IP}: ${port443_status}"
    else
        port443_status="NOT LISTENING"
        log "  Port 443 on ${KYPO_PUBLIC_IP}: ${port443_status} (Nginx will bind it)"
    fi

    log "Local port check completed (port 80: ${port80_status}, port 443: ${port443_status})"
}


# ─────────────────────────────────────────────
# Task 2: Nginx install and configure
# ─────────────────────────────────────────────

# Install Nginx if not already installed
install_nginx() {
    if command -v nginx >/dev/null 2>&1; then
        log "Nginx is already installed ($(nginx -v 2>&1 | head -1))"
        return 0
    fi

    log "Installing Nginx..."
    apt-get install -y nginx || {
        log_error "Failed to install Nginx"
        return 1
    }
    log_success "Nginx installed successfully"
}

# Create Nginx reverse proxy configuration
configure_nginx() {
    log "Configuring Nginx reverse proxy for KYPO_Node (${KYPO_NODE_IP})..."

    # Backup existing config if present
    if [ -f "$NGINX_CONF_FILE" ]; then
        cp "$NGINX_CONF_FILE" "$NGINX_CONF_BACKUP"
        log "Backed up existing config to ${NGINX_CONF_BACKUP}"
    fi

    # Ensure nginx stream module directory exists
    mkdir -p /etc/nginx/modules-enabled 2>/dev/null || true

    # Write HTTP proxy config
    cat > "$NGINX_CONF_FILE" << EOF
# KYPO Reverse Proxy — generated by 05-public-proxy-setup.sh
# HTTP — forward to KYPO_Node
server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://${KYPO_NODE_IP}:80;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket support
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
    }
}
EOF

    # HTTPS passthrough via stream module
    # On Ubuntu, ngx_stream_module must be explicitly loaded
    local stream_module_conf="/etc/nginx/modules-enabled/50-mod-stream.conf"
    local stream_module_path="/usr/lib/nginx/modules/ngx_stream_module.so"

    if [ -f "$stream_module_path" ]; then
        if [ ! -f "$stream_module_conf" ]; then
            echo "load_module ${stream_module_path};" > "$stream_module_conf"
            log "Loaded ngx_stream_module"
        fi
    else
        # Try installing libnginx-mod-stream
        log "Installing nginx stream module..."
        apt-get install -y libnginx-mod-stream 2>/dev/null || true
    fi

    local stream_conf="/etc/nginx/stream.d/kypo-https-passthrough.conf"
    mkdir -p /etc/nginx/stream.d

    cat > "$stream_conf" << EOF
# HTTPS SSL passthrough — generated by 05-public-proxy-setup.sh
server {
    listen 443;
    proxy_pass ${KYPO_NODE_IP}:443;
}
EOF

    # Ensure nginx.conf includes the stream block (outside http context)
    if ! grep -q "stream.d" /etc/nginx/nginx.conf 2>/dev/null; then
        cat >> /etc/nginx/nginx.conf << 'STREAMEOF'

# KYPO HTTPS passthrough (stream module)
stream {
    include /etc/nginx/stream.d/*.conf;
}
STREAMEOF
        log "Added stream block to nginx.conf for HTTPS passthrough"
    fi

    # Enable site: symlink into sites-enabled
    ln -sf "$NGINX_CONF_FILE" "$NGINX_ENABLED_DIR/kypo-proxy"
    log "Symlinked kypo-proxy into sites-enabled"

    # Remove default site if present
    if [ -L "$NGINX_ENABLED_DIR/default" ] || [ -f "$NGINX_ENABLED_DIR/default" ]; then
        rm -f "$NGINX_ENABLED_DIR/default"
        log "Removed default Nginx site"
    fi

    log_success "Nginx configuration written to ${NGINX_CONF_FILE}"
}

# Validate nginx config and reload; rollback on failure
validate_and_reload() {
    log "Validating Nginx configuration..."

    if nginx -t 2>&1; then
        log_success "Nginx configuration is valid"
        systemctl reload nginx
        log_success "Nginx reloaded successfully"
    else
        log_error "Nginx configuration test failed — rolling back"

        # Rollback: remove symlink
        rm -f "$NGINX_ENABLED_DIR/kypo-proxy"

        # Restore backup if available
        if [ -f "$NGINX_CONF_BACKUP" ]; then
            cp "$NGINX_CONF_BACKUP" "$NGINX_CONF_FILE"
            ln -sf "$NGINX_CONF_FILE" "$NGINX_ENABLED_DIR/kypo-proxy"
            log "Restored previous configuration from backup"
        else
            rm -f "$NGINX_CONF_FILE"
            log "No backup found — removed broken config file"
        fi

        log_error "Nginx was NOT reloaded. Fix the configuration and re-run."
        return 1
    fi
}

# Enable and start Nginx via systemd
enable_nginx() {
    log "Enabling and starting Nginx service..."
    systemctl enable --now nginx
    log_success "Nginx service enabled and started"
}


# ─────────────────────────────────────────────
# Task 3: E2E verification and main()
# ─────────────────────────────────────────────

# Perform end-to-end HTTP checks against the public endpoint
verify_e2e() {
    log "Running E2E verification against public endpoint (${KYPO_PUBLIC_IP})..."

    local urls=(
        "http://${KYPO_PUBLIC_IP}/"
        "https://${KYPO_PUBLIC_IP}/"
        "https://${KYPO_PUBLIC_IP}/keycloak/"
    )

    declare -A results

    for url in "${urls[@]}"; do
        local status_code
        status_code=$(curl -sk -o /dev/null -w "%{http_code}" \
            --max-time 15 \
            --connect-timeout 10 \
            "$url" 2>/dev/null) || status_code="FAILED"

        if [[ "$status_code" =~ ^(200|301|302)$ ]]; then
            results["$url"]="PASS (HTTP ${status_code})"
        else
            results["$url"]="FAIL (HTTP ${status_code:-no response})"
            log_error "E2E check failed for ${url}"
            log_error "  Status: ${status_code:-no response}"
            log_error "  Debug hints:"
            log_error "    • Verify Nginx is running:  systemctl status nginx"
            log_error "    • Check Nginx error log:    tail -50 /var/log/nginx/error.log"
            log_error "    • Test direct connectivity: nc -zw3 ${KYPO_NODE_IP} 80"
            log_error "    • Inspect Nginx config:     nginx -T"
        fi
    done

    # Print PASS/FAIL summary table
    echo ""
    echo "========================================"
    echo " E2E Verification Results"
    echo "========================================"
    printf "  %-45s %s\n" "URL" "STATUS"
    printf "  %-45s %s\n" "---" "------"
    local all_pass=true
    for url in "${urls[@]}"; do
        printf "  %-45s %s\n" "$url" "${results[$url]}"
        if [[ "${results[$url]}" == FAIL* ]]; then
            all_pass=false
        fi
    done
    echo "========================================"
    echo ""

    if $all_pass; then
        log_success "All E2E checks passed — KYPO is accessible via public endpoint"
    else
        log_warning "Some E2E checks failed — review the errors above"
    fi
}

# Main entry point
main() {
    log "=== Starting Public Proxy Setup ==="
    log "KYPO_NODE_IP  : ${KYPO_NODE_IP}"
    log "KYPO_PUBLIC_IP: ${KYPO_PUBLIC_IP}"

    check_connectivity
    check_local_ports
    install_nginx
    configure_nginx
    validate_and_reload
    enable_nginx
    verify_e2e

    log_success "=== Public Proxy Setup Completed ==="
}

# Run main function
main "$@"
